package main.java.model.entities;

// default package
// Generated 04-may-2021 10:46:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Impuestos generated by hbm2java
 */
@Entity
@Table(name = "impuestos", catalog = "tienda_online")
public class Impuestos implements java.io.Serializable {

	private Integer id;
	private Float impuesto;

	public Impuestos() {
	}

	public Impuestos(Float impuesto) {
		this.impuesto = impuesto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "impuesto", precision = 12, scale = 0)
	public Float getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(Float impuesto) {
		this.impuesto = impuesto;
	}

}
