package main.java.model.entities;

// default package
// Generated 04-may-2021 10:46:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OpcionesMenu generated by hbm2java
 */
@Entity
@Table(name = "opciones_menu", catalog = "tienda_arkaitz_rodriguez_martinez")
public class OpcionesMenu implements java.io.Serializable {

	private Integer id;
	private Integer idRol;
	private String opcion;

	public OpcionesMenu() {
	}

	public OpcionesMenu(Integer idRol, String opcion) {
		this.idRol = idRol;
		this.opcion = opcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_rol")
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Column(name = "opcion")
	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

}
